SRC=AIMoveTask.java BoardView.java ChessAI.java ChessClient.java ChessGame.java \
    MoveMaker.java RandomAI.java MinimaxAI.java AlphaBetaAI.java \
    BadEvalAI.java


main:
	javac -d . $(SRC)
	java chai.ChessClient

clean:
	rm -f ./chai/*.class
